steps:
  # Step 1: Build Docker image dari folder backend
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/be-Baretta", "."]
    dir: "notes-backend"  # Ganti jika folder kamu berbeda

  # Step 2: Push Docker image ke Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/be-Baretta"]

  # Step 3: Deploy image ke Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "be",  # Nama service Cloud Run
        "--image",
        "gcr.io/$PROJECT_ID/be-Baretta",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--timeout",
        "1000s",
        "--port",
        "8080",
        "-set-env-vars",
        "ACCESS_TOKEN_SECRET=${_ACCESS_TOKEN_SECRET},REFRESH_TOKEN_SECRET=${_REFRESH_TOKEN_SECRET},DB_HOST=${_DB_HOST},DB_NAME=${_DB_NAME},DB_PASSWORD=${_DB_PASSWORD},DB_USERNAME=${_DB_USERNAME}",
      ]

options:
  logging: CLOUD_LOGGING_ONLY
